CV_BG_GENERAL_DISTRIBUTION_STATISTICS = {
    'Дата': 'Date',
    'Направени тестове': 'Tests_Done',
    'Тестове за денонощие': 'Tests_Last_24_Done',
    'Потвърдени случаи': 'Total_Cases',
    'Активни случаи': 'Active_Cases',
    'Нови случаи за денонощие': 'Cases_Last_24_Cases',
    'Хоспитализирани': 'Total_Hospitalized',
    'Новохоспитализирани': 'Hospitalized_Last_24_Cases',
    'В интензивно отделение': 'Hospitalized_ICU',
    'Излекувани': 'Total_Discharged',
    'Излекувани за денонощие': 'Discharged_Last_24_Cases',
    'Починали': 'Total_Deceased',
    'Починали за денонощие': 'Deceased_Last_24_Cases',
}

CV_BG_DISTRIBUTION_BY_REGION = {
    'Дата': 'Date',
    'BLG_ALL': 'Blagoevgrad_Total',
    'BLG_ACT': 'Blagoevgrad_Active',
    'BGS_ALL': 'Burgas_Total',
    'BGS_ACT': 'Burgas_Active',
    'VAR_ALL': 'Varna_Total',
    'VAR_ACT': 'Varna_Active',
    'VTR_ALL': 'Veliko Tarnovo_Total',
    'VTR_ACT': 'Veliko Tarnovo_Active',
    'VID_ALL': 'Vidin_Total',
    'VID_ACT': 'Vidin_Active',
    'VRC_ALL': 'Vratsa_Total',
    'VRC_ACT': 'Vratsa_Active',
    'GAB_ALL': 'Gabrovo_Total',
    'GAB_ACT': 'Gabrovo_Active',
    'DOB_ALL': 'Dobrich_Total',
    'DOB_ACT': 'Dobrich_Active',
    'KRZ_ALL': 'Kardzhali_Total',
    'KRZ_ACT': 'Kardzhali_Active',
    'KNL_ALL': 'Kyustendil_Total',
    'KNL_ACT': 'Kyustendil_Active',
    'LOV_ALL': 'Lovetch_Total',
    'LOV_ACT': 'Lovetch_Active',
    'MON_ALL': 'Montana_Total',
    'MON_ACT': 'Montana_Active',
    'PAZ_ALL': 'Pazardzhik_Total',
    'PAZ_ACT': 'Pazardzhik_Active',
    'PER_ALL': 'Pernik_Total',
    'PER_ACT': 'Pernik_Active',
    'PVN_ALL': 'Pleven_Total',
    'PVN_ACT': 'Pleven_Active',
    'PDV_ALL': 'Plovdiv_Total',
    'PDV_ACT': 'Plovdiv_Active',
    'RAZ_ALL': 'Razgrad_Total',
    'RAZ_ACT': 'Razgrad_Active',
    'RSE_ALL': 'Ruse_Total',
    'RSE_ACT': 'Ruse_Active',
    'SLS_ALL': 'Silistra_Total',
    'SLS_ACT': 'Silistra_Active',
    'SLV_ALL': 'Sliven_Total',
    'SLV_ACT': 'Sliven_Active',
    'SML_ALL': 'Smolyan_Total',
    'SML_ACT': 'Smolyan_Active',
    'SFO_ALL': 'Sofia region_Total',
    'SFO_ACT': 'Sofia region_Active',
    'SOF_ALL': 'Sofia city_Total',
    'SOF_ACT': 'Sofia city_Active',
    'SZR_ALL': 'Stara Zagora_Total',
    'SZR_ACT': 'Stara Zagora_Active',
    'TGV_ALL': 'Targovishte_Total',
    'TGV_ACT': 'Targovishte_Active',
    'HKV_ALL': 'Haskovo_Total',
    'HKV_ACT': 'Haskovo_Active',
    'SHU_ALL': 'Shumen_Total',
    'SHU_ACT': 'Shumen_Active',
    'JAM_ALL': 'Yambol_Total',
    'JAM_ACT': 'Yambol_Active',
}

CV_BG_DISTRIBUTION_BY_AGE = {
    'Дата': 'Date',
    '0 - 1': '(0-1)',
    '1 - 5': '(1-5)',
    '6 - 9': '(6-9)',
    '10 - 14': '(10-14)',
    '15 - 19': '(15-19)',
    '0 - 19': '(0-19)',
    '20 - 29': '(20-29)',
    '30 - 39': '(30-39)',
    '40 - 49': '(40-49)',
    '50 - 59': '(50-59)',
    '60 - 69': '(60-69)',
    '70 - 79': '(70-79)',
    '80 - 89': '(80-89)',
    '90+': '90+',
}

CV_BG_DISTRIBUTION_BY_TESTS = {
    'Дата': 'Date',
    'Общо тестове': 'Total_Number_Test',
    'PCR тестове': 'PCR_Tests',
    'Антигени тестове': 'Antigen_Tests',
    'Общо тестове за денонощие': 'Total_Tests_Last_24_Hours',
    'PCR тестове за денонощие': 'PCR_Tests_Last_24_Hours',
    'Антигени тестове за денонощие': 'Antigen_Tests_Last_24_Hours',
    'Установени случаи общо': 'Total_Cases',
    'Установени случаи чрез PCR': 'Total_Cases_Through_PCR_Tests',
    'Установени случаи чрез антиген': 'Total_Cases_Through_Antigen_Tests',
    'Установени случаи за денонощие': 'Cases_Last_24_Hours',
    'Установени случаи за денонощие чрез PCR': 'Cases_Last_24_Hours_PCR',
    'Установени случаи за денонощие чрез антиген': 'Cases_Last_24_Hours_Antigen',
}

CV_BG_DECEASED_BY_GENDER_SEX = {
    'Дата': 'Date',
    'Пол': 'Sex',
    'Възрастова група': 'Age',
    'Брой починали': 'Mortality',
}

CV_BG_INFECTED_VACCINATED = {
    'Дата': 'Date',
    'Ваксина': 'Vaccine',
    'Пол': 'Sex',
    'Възрастова група': 'Age',
    'Брой заразени': 'Number_Infected',
}

CV_BG_HOSPITALIZED_VACCINATED = {
    'Дата': 'Date',
    'Ваксина': 'Vaccine',
    'Пол': 'Sex',
    'Възрастова група': 'Age',
    'Брой хоспитализирани': 'Number_Hospitalized',
}

CV_BG_ICU_VACCINATED = {
    'Дата': 'Date',
    'Ваксина': 'Vaccine',
    'Пол': 'Sex',
    'Възрастова група': 'Age',
    'Брой в интензивно отделение': 'Number_ICU',
}

CV_BG_DECEASED_VACCINATED = {
    'Дата': 'Date',
    'Ваксина': 'Vaccine',
    'Пол': 'Sex',
    'Възрастова група': 'Age',
    'Брой починали': 'Number_Deceased',
}
