EU_COUNTRIES_ISO_2_DECODES = {
    'AD': 'Andorra',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AT': 'Austria',
    'BE': 'Belgium',
    'BG': 'Bulgaria',
    'CH': 'Switzerland',
    'CY': 'Cyprus',
    'CZ': 'Czechia',
    'DE': 'Germany',
    'DK': 'Denmark',
    'EE': 'Estonia',
    'EL': 'Greece',
    'ES': 'Spain',
    'FI': 'Finland',
    'FR': 'France',
    'GE': 'Georgia',
    'HR': 'Croatia',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'IT': 'Italy',
    'LI': 'Liechtenstein',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'LV': 'Latvia',
    'ME': 'Montenegro',
    'MT': 'Malta',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'PL': 'Poland',
    'PT': 'Portugal',
    'RO': 'Romania',
    'RS': 'Serbia',
    'SE': 'Sweden',
    'SI': 'Slovenia',
    'SK': 'Slovakia',
    'UK': 'United Kingdom',
}

EU_DECODE_NUTS3_REGIONS = {
    'BE': 'Belgium',
    'BE1': 'Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest',
    'BE10': 'Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest',
    'BE100': 'Arr. de Bruxelles-Capitale/Arr. Brussel-Hoofdstad',
    'BE2': 'Vlaams Gewest',
    'BE21': 'Prov. Antwerpen',
    'BE211': 'Arr. Antwerpen',
    'BE212': 'Arr. Mechelen',
    'BE213': 'Arr. Turnhout',
    'BE22': 'Prov. Limburg (BE)',
    'BE221': 'Arr. Hasselt (NUTS 2016)',
    'BE222': 'Arr. Maaseik (NUTS 2016)',
    'BE223': 'Arr. Tongeren',
    'BE224': 'Arr. Hasselt',
    'BE225': 'Arr. Maaseik',
    'BE23': 'Prov. Oost-Vlaanderen',
    'BE231': 'Arr. Aalst',
    'BE232': 'Arr. Dendermonde',
    'BE233': 'Arr. Eeklo',
    'BE234': 'Arr. Gent',
    'BE235': 'Arr. Oudenaarde',
    'BE236': 'Arr. Sint-Niklaas',
    'BE24': 'Prov. Vlaams-Brabant',
    'BE241': 'Arr. Halle-Vilvoorde',
    'BE242': 'Arr. Leuven',
    'BE25': 'Prov. West-Vlaanderen',
    'BE251': 'Arr. Brugge',
    'BE252': 'Arr. Diksmuide',
    'BE253': 'Arr. Ieper',
    'BE254': 'Arr. Kortrijk',
    'BE255': 'Arr. Oostende',
    'BE256': 'Arr. Roeselare',
    'BE257': 'Arr. Tielt',
    'BE258': 'Arr. Veurne',
    'BE3': 'Région wallonne',
    'BE31': 'Prov. Brabant wallon',
    'BE310': 'Arr. Nivelles',
    'BE32': 'Prov. Hainaut',
    'BE321': 'Arr. Ath (NUTS 2016)',
    'BE322': 'Arr. Charleroi (NUTS 2016)',
    'BE323': 'Arr. Mons',
    'BE324': 'Arr. Mouscron (NUTS 2016)',
    'BE325': 'Arr. Soignies (NUTS 2016)',
    'BE326': 'Arr. Thuin (NUTS 2016)',
    'BE327': 'Arr. Tournai (NUTS 2016)',
    'BE328': 'Arr. Tournai-Mouscron',
    'BE329': 'Arr. La Louvière',
    'BE32A': 'Arr. Ath',
    'BE32B': 'Arr. Charleroi',
    'BE32C': 'Arr. Soignies',
    'BE32D': 'Arr. Thuin',
    'BE33': 'Prov. Liège',
    'BE331': 'Arr. Huy',
    'BE332': 'Arr. Liège',
    'BE334': 'Arr. Waremme',
    'BE335': 'Arr. Verviers - communes francophones',
    'BE336': 'Bezirk Verviers - Deutschsprachige Gemeinschaft',
    'BE34': 'Prov. Luxembourg (BE)',
    'BE341': 'Arr. Arlon',
    'BE342': 'Arr. Bastogne',
    'BE343': 'Arr. Marche-en-Famenne',
    'BE344': 'Arr. Neufchâteau',
    'BE345': 'Arr. Virton',
    'BE35': 'Prov. Namur',
    'BE351': 'Arr. Dinant',
    'BE352': 'Arr. Namur',
    'BE353': 'Arr. Philippeville',
    'BG': 'Bulgaria',
    'BG3': 'Severna i yugoiztochna Bulgaria',
    'BG31': 'Severozapaden',
    'BG311': 'Vidin',
    'BG312': 'Montana',
    'BG313': 'Vratsa',
    'BG314': 'Pleven',
    'BG315': 'Lovech',
    'BG32': 'Severen tsentralen',
    'BG321': 'Veliko Tarnovo',
    'BG322': 'Gabrovo',
    'BG323': 'Ruse',
    'BG324': 'Razgrad',
    'BG325': 'Silistra',
    'BG33': 'Severoiztochen',
    'BG331': 'Varna',
    'BG332': 'Dobrich',
    'BG333': 'Shumen',
    'BG334': 'Targovishte',
    'BG34': 'Yugoiztochen',
    'BG341': 'Burgas',
    'BG342': 'Sliven',
    'BG343': 'Yambol',
    'BG344': 'Stara Zagora',
    'BG4': 'Yugozapadna i yuzhna tsentralna Bulgaria',
    'BG41': 'Yugozapaden',
    'BG411': 'Sofia (stolitsa)',
    'BG412': 'Sofia',
    'BG413': 'Blagoevgrad',
    'BG414': 'Pernik',
    'BG415': 'Kyustendil',
    'BG42': 'Yuzhen tsentralen',
    'BG421': 'Plovdiv',
    'BG422': 'Haskovo',
    'BG423': 'Pazardzhik',
    'BG424': 'Smolyan',
    'BG425': 'Kardzhali',
    'CZ': 'Czechia',
    'CZ0': 'Cesko',
    'CZ01': 'Praha',
    'CZ010': 'Hlavní mesto Praha',
    'CZ02': 'Strední Cechy',
    'CZ020': 'Stredoceský kraj',
    'CZ03': 'Jihozápad',
    'CZ031': 'Jihocecký kraj',
    'CZ032': 'Plzenský kraj',
    'CZ04': 'Severozápad',
    'CZ041': 'Karlovarský kraj',
    'CZ042': 'Ústecký kraj',
    'CZ05': 'Severovýchod',
    'CZ051': 'Liberecký kraj',
    'CZ052': 'Královéhradecký kraj',
    'CZ053': 'Pardubický kraj',
    'CZ06': 'Jihovýchod',
    'CZ063': 'Kraj Vysocina',
    'CZ064': 'Jihomoravský kraj',
    'CZ07': 'Strední Morava',
    'CZ071': 'Olomoucký kraj',
    'CZ072': 'Zlínský kraj',
    'CZ08': 'Moravskoslezsko',
    'CZ080': 'Moravskoslezský kraj',
    'DK': 'Denmark',
    'DK0': 'Danmark',
    'DK01': 'Hovedstaden',
    'DK011': 'Byen København',
    'DK012': 'Københavns omegn',
    'DK013': 'Nordsjælland',
    'DK014': 'Bornholm',
    'DK02': 'Sjælland',
    'DK021': 'Østsjælland',
    'DK022': 'Vest- og Sydsjælland',
    'DK03': 'Syddanmark',
    'DK031': 'Fyn',
    'DK032': 'Sydjylland',
    'DK04': 'Midtjylland',
    'DK041': 'Vestjylland',
    'DK042': 'Østjylland',
    'DK05': 'Nordjylland',
    'DK050': 'Nordjylland',
    'DE': 'Germany (until 1990 former territory of the FRG)',
    'DE1': 'Baden-Württemberg',
    'DE2': 'Bayern',
    'DE3': 'Berlin',
    'DE4': 'Brandenburg',
    'DE5': 'Bremen',
    'DE6': 'Hamburg',
    'DE7': 'Hessen',
    'DE8': 'Mecklenburg-Vorpommern',
    'DE9': 'Niedersachsen',
    'DEA': 'Nordrhein-Westfalen',
    'DEB': 'Rheinland-Pfalz',
    'DEC': 'Saarland',
    'DED': 'Sachsen',
    'DEE': 'Sachsen-Anhalt',
    'DEF': 'Schleswig-Holstein',
    'DEG': 'Thüringen',
    'EE': 'Estonia',
    'EE0': 'Eesti',
    'EE00': 'Eesti',
    'EE001': 'Põhja-Eesti',
    'EE004': 'Lääne-Eesti',
    'EE006': 'Kesk-Eesti (NUTS 2016)',
    'EE007': 'Kirde-Eesti (NUTS 2016)',
    'EE008': 'Lõuna-Eesti',
    'EL': 'Greece',
    'EL3': 'Attiki',
    'EL30': 'Attiki',
    'EL301': 'Voreios Tomeas Athinon',
    'EL302': 'Dytikos Tomeas Athinon',
    'EL303': 'Kentrikos Tomeas Athinon',
    'EL304': 'Notios Tomeas Athinon',
    'EL305': 'Anatoliki Attiki',
    'EL306': 'Dytiki Attiki',
    'EL307': 'Peiraias, Nisoi',
    'EL4': 'Nisia Aigaiou, Kriti',
    'EL41': 'Voreio Aigaio',
    'EL411': 'Lesvos, Limnos',
    'EL412': 'Ikaria, Samos',
    'EL413': 'Chios',
    'EL42': 'Notio Aigaio',
    'EL421': 'Kalymnos, Karpathos, Kasos, Kos, Rodos',
    'EL422': 'Andros, Thira, Kea, Milos, Mykonos, Naxos, Paros, Syros, Tinos',
    'EL43': 'Kriti',
    'EL431': 'Irakleio',
    'EL432': 'Lasithi',
    'EL433': 'Rethymni',
    'EL434': 'Chania',
    'EL5': 'Voreia Ellada',
    'EL51': 'Anatoliki Makedonia, Thraki',
    'EL511': 'Evros',
    'EL512': 'Xanthi',
    'EL513': 'Rodopi',
    'EL514': 'Drama',
    'EL515': 'Thasos, Kavala',
    'EL52': 'Kentriki Makedonia',
    'EL521': 'Imathia',
    'EL522': 'Thessaloniki',
    'EL523': 'Kilkis',
    'EL524': 'Pella',
    'EL525': 'Pieria',
    'EL526': 'Serres',
    'EL527': 'Chalkidiki',
    'EL53': 'Dytiki Makedonia',
    'EL531': 'Grevena, Kozani',
    'EL532': 'Kastoria',
    'EL533': 'Florina',
    'EL54': 'Ipeiros',
    'EL541': 'Arta, Preveza',
    'EL542': 'Thesprotia',
    'EL543': 'Ioannina',
    'EL6': 'Kentriki Ellada',
    'EL61': 'Thessalia',
    'EL611': 'Karditsa, Trikala',
    'EL612': 'Larisa',
    'EL613': 'Magnisia',
    'EL62': 'Ionia Nisia',
    'EL621': 'Zakynthos',
    'EL622': 'Kerkyra',
    'EL623': 'Ithaki, Kefallinia',
    'EL624': 'Lefkada',
    'EL63': 'Dytiki Ellada',
    'EL631': 'Aitoloakarnania',
    'EL632': 'Achaia',
    'EL633': 'Ileia',
    'EL64': 'Sterea Ellada',
    'EL641': 'Voiotia',
    'EL642': 'Evvoia',
    'EL643': 'Evrytania',
    'EL644': 'Fthiotida',
    'EL645': 'Fokida',
    'EL65': 'Peloponnisos',
    'EL651': 'Argolida, Arkadia',
    'EL652': 'Korinthia',
    'EL653': 'Lakonia, Messinia',
    'ES': 'Spain',
    'ES1': 'Noroeste (ES)',
    'ES11': 'Galicia',
    'ES111': 'A Coruña',
    'ES112': 'Lugo',
    'ES113': 'Ourense',
    'ES114': 'Pontevedra',
    'ES12': 'Principado de Asturias',
    'ES120': 'Asturias',
    'ES13': 'Cantabria',
    'ES130': 'Cantabria',
    'ES2': 'Noreste (ES)',
    'ES21': 'País Vasco',
    'ES211': 'Araba/Álava',
    'ES212': 'Gipuzkoa',
    'ES213': 'Bizkaia',
    'ES22': 'Comunidad Foral de Navarra',
    'ES220': 'Navarra',
    'ES23': 'La Rioja',
    'ES230': 'La Rioja',
    'ES24': 'Aragón',
    'ES241': 'Huesca',
    'ES242': 'Teruel',
    'ES243': 'Zaragoza',
    'ES3': 'Comunidad de Madrid',
    'ES30': 'Comunidad de Madrid',
    'ES300': 'Madrid',
    'ES4': 'Centro (ES)',
    'ES41': 'Castilla y León',
    'ES411': 'Ávila',
    'ES412': 'Burgos',
    'ES413': 'León',
    'ES414': 'Palencia',
    'ES415': 'Salamanca',
    'ES416': 'Segovia',
    'ES417': 'Soria',
    'ES418': 'Valladolid',
    'ES419': 'Zamora',
    'ES42': 'Castilla-la Mancha',
    'ES421': 'Albacete',
    'ES422': 'Ciudad Real',
    'ES423': 'Cuenca',
    'ES424': 'Guadalajara',
    'ES425': 'Toledo',
    'ES43': 'Extremadura',
    'ES431': 'Badajoz',
    'ES432': 'Cáceres',
    'ES5': 'Este (ES)',
    'ES51': 'Cataluña',
    'ES511': 'Barcelona',
    'ES512': 'Girona',
    'ES513': 'Lleida',
    'ES514': 'Tarragona',
    'ES52': 'Comunitat Valenciana',
    'ES521': 'Alicante/Alacant',
    'ES522': 'Castellón/Castelló',
    'ES523': 'Valencia/València',
    'ES53': 'Illes Balears',
    'ES531': 'Eivissa, Formentera',
    'ES532': 'Mallorca',
    'ES533': 'Menorca',
    'ES6': 'Sur (ES)',
    'ES61': 'Andalucía',
    'ES611': 'Almería',
    'ES612': 'Cádiz',
    'ES613': 'Córdoba',
    'ES614': 'Granada',
    'ES615': 'Huelva',
    'ES616': 'Jaén',
    'ES617': 'Málaga',
    'ES618': 'Sevilla',
    'ES62': 'Región de Murcia',
    'ES620': 'Murcia',
    'ES63': 'Ciudad de Ceuta',
    'ES630': 'Ceuta',
    'ES64': 'Ciudad de Melilla',
    'ES640': 'Melilla',
    'ES7': 'Canarias',
    'ES70': 'Canarias',
    'ES703': 'El Hierro',
    'ES704': 'Fuerteventura',
    'ES705': 'Gran Canaria',
    'ES706': 'La Gomera',
    'ES707': 'La Palma',
    'ES708': 'Lanzarote',
    'ES709': 'Tenerife',
    'FR': 'France',
    'FR1': 'Île de France',
    'FR10': 'Île de France',
    'FR101': 'Paris',
    'FR102': 'Seine-et-Marne',
    'FR103': 'Yvelines',
    'FR104': 'Essonne',
    'FR105': 'Hauts-de-Seine',
    'FR106': 'Seine-Saint-Denis',
    'FR107': 'Val-de-Marne',
    'FR108': 'Val-dOise',
    'FRB': 'Centre - Val de Loire',
    'FRB0': 'Centre - Val de Loire',
    'FRB01': 'Cher',
    'FRB02': 'Eure-et-Loir',
    'FRB03': 'Indre',
    'FRB04': 'Indre-et-Loire',
    'FRB05': 'Loir-et-Cher',
    'FRB06': 'Loiret',
    'FRC': 'Bourgogne - Franche-Comté',
    'FRC1': 'Bourgogne',
    'FRC11': 'Côte-dOr',
    'FRC12': 'Nièvre',
    'FRC13': 'Saône-et-Loire',
    'FRC14': 'Yonne',
    'FRC2': 'Franche-Comté',
    'FRC21': 'Doubs',
    'FRC22': 'Jura',
    'FRC23': 'Haute-Saône',
    'FRC24': 'Territoire de Belfort',
    'FRD': 'Normandie',
    'FRD1': 'Basse-Normandie',
    'FRD11': 'Calvados',
    'FRD12': 'Manche',
    'FRD13': 'Orne',
    'FRD2': 'Haute-Normandie',
    'FRD21': 'Eure',
    'FRD22': 'Seine-Maritime',
    'FRE': 'Hauts-de-France',
    'FRE1': 'Nord-Pas-de-Calais',
    'FRE11': 'Nord',
    'FRE12': 'Pas-de-Calais',
    'FRE2': 'Picardie',
    'FRE21': 'Aisne',
    'FRE22': 'Oise',
    'FRE23': 'Somme',
    'FRF': 'Grand Est',
    'FRF1': 'Alsace',
    'FRF11': 'Bas-Rhin',
    'FRF12': 'Haut-Rhin',
    'FRF2': 'Champagne-Ardenne',
    'FRF21': 'Ardennes',
    'FRF22': 'Aube',
    'FRF23': 'Marne',
    'FRF24': 'Haute-Marne',
    'FRF3': 'Lorraine',
    'FRF31': 'Meurthe-et-Moselle',
    'FRF32': 'Meuse',
    'FRF33': 'Moselle',
    'FRF34': 'Vosges',
    'FRG': 'Pays-de-la-Loire',
    'FRG0': 'Pays-de-la-Loire',
    'FRG01': 'Loire-Atlantique',
    'FRG02': 'Maine-et-Loire',
    'FRG03': 'Mayenne',
    'FRG04': 'Sarthe',
    'FRG05': 'Vendée',
    'FRH': 'Bretagne',
    'FRH0': 'Bretagne',
    'FRH01': 'Côtes-dArmor',
    'FRH02': 'Finistère',
    'FRH03': 'Ille-et-Vilaine',
    'FRH04': 'Morbihan',
    'FRI': 'Nouvelle-Aquitaine',
    'FRI1': 'Aquitaine',
    'FRI11': 'Dordogne',
    'FRI12': 'Gironde',
    'FRI13': 'Landes',
    'FRI14': 'Lot-et-Garonne',
    'FRI15': 'Pyrénées-Atlantiques',
    'FRI2': 'Limousin',
    'FRI21': 'Corrèze',
    'FRI22': 'Creuse',
    'FRI23': 'Haute-Vienne',
    'FRI3': 'Poitou-Charentes',
    'FRI31': 'Charente',
    'FRI32': 'Charente-Maritime',
    'FRI33': 'Deux-Sèvres',
    'FRI34': 'Vienne',
    'FRJ': 'Occitanie',
    'FRJ1': 'Languedoc-Roussillon',
    'FRJ11': 'Aude',
    'FRJ12': 'Gard',
    'FRJ13': 'Hérault',
    'FRJ14': 'Lozère',
    'FRJ15': 'Pyrénées-Orientales',
    'FRJ2': 'Midi-Pyrénées',
    'FRJ21': 'Ariège',
    'FRJ22': 'Aveyron',
    'FRJ23': 'Haute-Garonne',
    'FRJ24': 'Gers',
    'FRJ25': 'Lot',
    'FRJ26': 'Hautes-Pyrénées',
    'FRJ27': 'Tarn',
    'FRJ28': 'Tarn-et-Garonne',
    'FRK': 'Auvergne - Rhône-Alpes',
    'FRK1': 'Auvergne',
    'FRK11': 'Allier',
    'FRK12': 'Cantal',
    'FRK13': 'Haute-Loire',
    'FRK14': 'Puy-de-Dôme',
    'FRK2': 'Rhône-Alpes',
    'FRK21': 'Ain',
    'FRK22': 'Ardèche',
    'FRK23': 'Drôme',
    'FRK24': 'Isère',
    'FRK25': 'Loire',
    'FRK26': 'Rhône',
    'FRK27': 'Savoie',
    'FRK28': 'Haute-Savoie',
    'FRL': 'Provence-Alpes-Côte dAzur',
    'FRL0': 'Provence-Alpes-Côte dAzur',
    'FRL01': 'Alpes-de-Haute-Provence',
    'FRL02': 'Hautes-Alpes',
    'FRL03': 'Alpes-Maritimes',
    'FRL04': 'Bouches-du-Rhône',
    'FRL05': 'Var',
    'FRL06': 'Vaucluse',
    'FRM': 'Corse',
    'FRM0': 'Corse',
    'FRM01': 'Corse-du-Sud',
    'FRM02': 'Haute-Corse',
    'FRY': 'RUP FR - Régions ultrapériphériques françaises',
    'FRY1': 'Guadeloupe',
    'FRY10': 'Guadeloupe',
    'FRY2': 'Martinique',
    'FRY20': 'Martinique',
    'FRY3': 'Guyane',
    'FRY30': 'Guyane',
    'FRY4': 'La Réunion',
    'FRY40': 'La Réunion',
    'FRY5': 'Mayotte',
    'FRY50': 'Mayotte',
    'HR': 'Croatia',
    'HR0': 'Hrvatska',
    'IT': 'Italy',
    'ITC': 'Nord-Ovest',
    'ITC1': 'Piemonte',
    'ITC11': 'Torino',
    'ITC12': 'Vercelli',
    'ITC13': 'Biella',
    'ITC14': 'Verbano-Cusio-Ossola',
    'ITC15': 'Novara',
    'ITC16': 'Cuneo',
    'ITC17': 'Asti',
    'ITC18': 'Alessandria',
    'ITC2': 'Valle dAosta/Vallée dAoste',
    'ITC20': 'Valle dAosta/Vallée dAoste',
    'ITC3': 'Liguria',
    'ITC31': 'Imperia',
    'ITC32': 'Savona',
    'ITC33': 'Genova',
    'ITC34': 'La Spezia',
    'ITC4': 'Lombardia',
    'ITC41': 'Varese',
    'ITC42': 'Como',
    'ITC43': 'Lecco',
    'ITC44': 'Sondrio',
    'ITC46': 'Bergamo',
    'ITC47': 'Brescia',
    'ITC48': 'Pavia',
    'ITC49': 'Lodi',
    'ITC4A': 'Cremona',
    'ITC4B': 'Mantova',
    'ITC4C': 'Milano',
    'ITC4D': 'Monza e della Brianza',
    'ITH': 'Nord-Est',
    'ITH1': 'Provincia Autonoma di Bolzano/Bozen',
    'ITH10': 'Bolzano-Bozen',
    'ITH2': 'Provincia Autonoma di Trento',
    'ITH20': 'Trento',
    'ITH3': 'Veneto',
    'ITH31': 'Verona',
    'ITH32': 'Vicenza',
    'ITH33': 'Belluno',
    'ITH34': 'Treviso',
    'ITH35': 'Venezia',
    'ITH36': 'Padova',
    'ITH37': 'Rovigo',
    'ITH4': 'Friuli-Venezia Giulia',
    'ITH41': 'Pordenone',
    'ITH42': 'Udine',
    'ITH43': 'Gorizia',
    'ITH44': 'Trieste',
    'ITH5': 'Emilia-Romagna',
    'ITH51': 'Piacenza',
    'ITH52': 'Parma',
    'ITH53': 'Reggio nellEmilia',
    'ITH54': 'Modena',
    'ITH55': 'Bologna',
    'ITH56': 'Ferrara',
    'ITH57': 'Ravenna',
    'ITH58': 'Forlì-Cesena',
    'ITH59': 'Rimini',
    'ITI': 'Centro (IT)',
    'ITI1': 'Toscana',
    'ITI11': 'Massa-Carrara',
    'ITI12': 'Lucca',
    'ITI13': 'Pistoia',
    'ITI14': 'Firenze',
    'ITI15': 'Prato',
    'ITI16': 'Livorno',
    'ITI17': 'Pisa',
    'ITI18': 'Arezzo',
    'ITI19': 'Siena',
    'ITI1A': 'Grosseto',
    'ITI2': 'Umbria',
    'ITI21': 'Perugia',
    'ITI22': 'Terni',
    'ITI3': 'Marche',
    'ITI31': 'Pesaro e Urbino',
    'ITI32': 'Ancona',
    'ITI33': 'Macerata',
    'ITI34': 'Ascoli Piceno',
    'ITI35': 'Fermo',
    'ITI4': 'Lazio',
    'ITI41': 'Viterbo',
    'ITI42': 'Rieti',
    'ITI43': 'Roma',
    'ITI44': 'Latina',
    'ITI45': 'Frosinone',
    'ITF': 'Sud',
    'ITF1': 'Abruzzo',
    'ITF11': 'LAquila',
    'ITF12': 'Teramo',
    'ITF13': 'Pescara',
    'ITF14': 'Chieti',
    'ITF2': 'Molise',
    'ITF21': 'Isernia',
    'ITF22': 'Campobasso',
    'ITF3': 'Campania',
    'ITF31': 'Caserta',
    'ITF32': 'Benevento',
    'ITF33': 'Napoli',
    'ITF34': 'Avellino',
    'ITF35': 'Salerno',
    'ITF4': 'Puglia',
    'ITF43': 'Taranto',
    'ITF44': 'Brindisi',
    'ITF45': 'Lecce',
    'ITF46': 'Foggia',
    'ITF47': 'Bari',
    'ITF48': 'Barletta-Andria-Trani',
    'ITF5': 'Basilicata',
    'ITF51': 'Potenza',
    'ITF52': 'Matera',
    'ITF6': 'Calabria',
    'ITF61': 'Cosenza',
    'ITF62': 'Crotone',
    'ITF63': 'Catanzaro',
    'ITF64': 'Vibo Valentia',
    'ITF65': 'Reggio di Calabria',
    'ITG': 'Isole',
    'ITG1': 'Sicilia',
    'ITG11': 'Trapani',
    'ITG12': 'Palermo',
    'ITG13': 'Messina',
    'ITG14': 'Agrigento',
    'ITG15': 'Caltanissetta',
    'ITG16': 'Enna',
    'ITG17': 'Catania',
    'ITG18': 'Ragusa',
    'ITG19': 'Siracusa',
    'ITG2': 'Sardegna',
    'ITG25': 'Sassari (NUTS 2016)',
    'ITG26': 'Nuoro (NUTS 2016)',
    'ITG27': 'Cagliari (NUTS 2016)',
    'ITG28': 'Oristano (NUTS 2016)',
    'ITG29': 'Olbia-Tempio (NUTS 2016)',
    'ITG2A': 'Ogliastra (NUTS 2016)',
    'ITG2B': 'Medio Campidano (NUTS 2016)',
    'ITG2C': 'Carbonia-Iglesias (NUTS 2016)',
    'ITG2D': 'Sassari',
    'ITG2E': 'Nuoro',
    'ITG2F': 'Cagliari',
    'ITG2G': 'Oristano',
    'ITG2H': 'Sud Sardegna',
    'CY': 'Cyprus',
    'CY0': 'Kypros',
    'CY00': 'Kypros',
    'CY000': 'Kypros',
    'LV': 'Latvia',
    'LV0': 'Latvija',
    'LV00': 'Latvija',
    'LV003': 'Kurzeme',
    'LV005': 'Latgale',
    'LV006': 'Riga',
    'LV007': 'Pieriga',
    'LV008': 'Vidzeme',
    'LV009': 'Zemgale',
    'LT': 'Lithuania',
    'LT0': 'Lietuva',
    'LT01': 'Sostines regionas',
    'LT011': 'Vilniaus apskritis',
    'LT02': 'Vidurio ir vakaru Lietuvos regionas',
    'LT021': 'Alytaus apskritis',
    'LT022': 'Kauno apskritis',
    'LT023': 'Klaipedos apskritis',
    'LT024': 'Marijampoles apskritis',
    'LT025': 'Panevezio apskritis',
    'LT026': 'Siauliu apskritis',
    'LT027': 'Taurages apskritis',
    'LT028': 'Telsiu apskritis',
    'LT029': 'Utenos apskritis',
    'LU': 'Luxembourg',
    'LU0': 'Luxembourg',
    'LU00': 'Luxembourg',
    'LU000': 'Luxembourg',
    'HU': 'Hungary',
    'HU1': 'Közép-Magyarország',
    'HU11': 'Budapest',
    'HU110': 'Budapest',
    'HU12': 'Pest',
    'HU120': 'Pest',
    'HU2': 'Dunántúl',
    'HU21': 'Közép-Dunántúl',
    'HU211': 'Fejér',
    'HU212': 'Komárom-Esztergom',
    'HU213': 'Veszprém',
    'HU22': 'Nyugat-Dunántúl',
    'HU221': 'Gyor-Moson-Sopron',
    'HU222': 'Vas',
    'HU223': 'Zala',
    'HU23': 'Dél-Dunántúl',
    'HU231': 'Baranya',
    'HU232': 'Somogy',
    'HU233': 'Tolna',
    'HU3': 'Alföld és Észak',
    'HU31': 'Észak-Magyarország',
    'HU311': 'Borsod-Abaúj-Zemplén',
    'HU312': 'Heves',
    'HU313': 'Nógrád',
    'HU32': 'Észak-Alföld',
    'HU321': 'Hajdú-Bihar',
    'HU322': 'Jász-Nagykun-Szolnok',
    'HU323': 'Szabolcs-Szatmár-Bereg',
    'HU33': 'Dél-Alföld',
    'HU331': 'Bács-Kiskun',
    'HU332': 'Békés',
    'HU333': 'Csongrád',
    'MT': 'Malta',
    'MT0': 'Malta',
    'MT00': 'Malta',
    'NL': 'Netherlands',
    'NL1': 'Noord-Nederland',
    'NL11': 'Groningen',
    'NL111': 'Oost-Groningen',
    'NL112': 'Delfzijl en omgeving',
    'NL113': 'Overig Groningen',
    'NL12': 'Friesland (NL)',
    'NL124': 'Noord-Friesland',
    'NL125': 'Zuidwest-Friesland',
    'NL126': 'Zuidoost-Friesland',
    'NL13': 'Drenthe',
    'NL131': 'Noord-Drenthe',
    'NL132': 'Zuidoost-Drenthe',
    'NL133': 'Zuidwest-Drenthe',
    'NL2': 'Oost-Nederland',
    'NL21': 'Overijssel',
    'NL211': 'Noord-Overijssel',
    'NL212': 'Zuidwest-Overijssel',
    'NL213': 'Twente',
    'NL22': 'Gelderland',
    'NL221': 'Veluwe',
    'NL224': 'Zuidwest-Gelderland',
    'NL225': 'Achterhoek',
    'NL226': 'Arnhem/Nijmegen',
    'NL23': 'Flevoland',
    'NL230': 'Flevoland',
    'NL3': 'West-Nederland',
    'NL31': 'Utrecht',
    'NL310': 'Utrecht',
    'NL32': 'Noord-Holland',
    'NL321': 'Kop van Noord-Holland',
    'NL323': 'IJmond',
    'NL324': 'Agglomeratie Haarlem',
    'NL325': 'Zaanstreek',
    'NL327': 'Het Gooi en Vechtstreek',
    'NL328': 'Alkmaar en omgeving',
    'NL329': 'Groot-Amsterdam',
    'NL33': 'Zuid-Holland',
    'NL332': 'Agglomeraties Gravenhage',
    'NL333': 'Delft en Westland',
    'NL337': 'Agglomeratie Leiden en Bollenstreek',
    'NL33A': 'Zuidoost-Zuid-Holland',
    'NL33B': 'Oost-Zuid-Holland',
    'NL33C': 'Groot-Rijnmond',
    'NL34': 'Zeeland',
    'NL341': 'Zeeuwsch-Vlaanderen',
    'NL342': 'Overig Zeeland',
    'NL4': 'Zuid-Nederland',
    'NL41': 'Noord-Brabant',
    'NL411': 'West-Noord-Brabant',
    'NL412': 'Midden-Noord-Brabant',
    'NL413': 'Noordoost-Noord-Brabant',
    'NL414': 'Zuidoost-Noord-Brabant',
    'NL42': 'Limburg (NL)',
    'NL421': 'Noord-Limburg',
    'NL422': 'Midden-Limburg',
    'NL423': 'Zuid-Limburg',
    'AT': 'Austria',
    'AT1': 'Ostösterreich',
    'AT11': 'Burgenland (AT)',
    'AT111': 'Mittelburgenland',
    'AT112': 'Nordburgenland',
    'AT113': 'Südburgenland',
    'AT12': 'Niederösterreich',
    'AT121': 'Mostviertel-Eisenwurzen',
    'AT122': 'Niederösterreich-Süd',
    'AT123': 'Sankt Pölten',
    'AT124': 'Waldviertel',
    'AT125': 'Weinviertel',
    'AT126': 'Wiener Umland/Nordteil',
    'AT127': 'Wiener Umland/Südteil',
    'AT13': 'Wien',
    'AT130': 'Wien',
    'AT2': 'Südösterreich',
    'AT21': 'Kärnten',
    'AT211': 'Klagenfurt-Villach',
    'AT212': 'Oberkärnten',
    'AT213': 'Unterkärnten',
    'AT22': 'Steiermark',
    'AT221': 'Graz',
    'AT222': 'Liezen',
    'AT223': 'Östliche Obersteiermark',
    'AT224': 'Oststeiermark',
    'AT225': 'West- und Südsteiermark',
    'AT226': 'Westliche Obersteiermark',
    'AT3': 'Westösterreich',
    'AT31': 'Oberösterreich',
    'AT311': 'Innviertel',
    'AT312': 'Linz-Wels',
    'AT313': 'Mühlviertel',
    'AT314': 'Steyr-Kirchdorf',
    'AT315': 'Traunviertel',
    'AT32': 'Salzburg',
    'AT321': 'Lungau',
    'AT322': 'Pinzgau-Pongau',
    'AT323': 'Salzburg und Umgebung',
    'AT33': 'Tirol',
    'AT331': 'Außerfern',
    'AT332': 'Innsbruck',
    'AT333': 'Osttirol',
    'AT334': 'Tiroler Oberland',
    'AT335': 'Tiroler Unterland',
    'AT34': 'Vorarlberg',
    'AT341': 'Bludenz-Bregenzer Wald',
    'AT342': 'Rheintal-Bodenseegebiet',
    'PL': 'Poland',
    'PL2': 'Makroregion Poludniowy',
    'PL21': 'Malopolskie',
    'PL213': 'Miasto Kraków',
    'PL214': 'Krakowski',
    'PL217': 'Tarnowski',
    'PL218': 'Nowosadecki',
    'PL219': 'Nowotarski',
    'PL21A': 'Oswiecimski',
    'PL22': 'Slaskie',
    'PL224': 'Czestochowski',
    'PL225': 'Bielski',
    'PL227': 'Rybnicki',
    'PL228': 'Bytomski',
    'PL229': 'Gliwicki',
    'PL22A': 'Katowicki',
    'PL22B': 'Sosnowiecki',
    'PL22C': 'Tyski',
    'PL4': 'Makroregion Pólnocno-Zachodni',
    'PL41': 'Wielkopolskie',
    'PL411': 'Pilski',
    'PL414': 'Koninski',
    'PL415': 'Miasto Poznan',
    'PL416': 'Kaliski',
    'PL417': 'Leszczynski',
    'PL418': 'Poznanski',
    'PL42': 'Zachodniopomorskie',
    'PL424': 'Miasto Szczecin',
    'PL426': 'Koszalinski',
    'PL427': 'Szczecinecko-pyrzycki',
    'PL428': 'Szczecinski',
    'PL43': 'Lubuskie',
    'PL431': 'Gorzowski',
    'PL432': 'Zielonogórski',
    'PL5': 'Makroregion Poludniowo-Zachodni',
    'PL51': 'Dolnoslaskie',
    'PL514': 'Miasto Wroclaw',
    'PL515': 'Jeleniogórski',
    'PL516': 'Legnicko-Glogowski',
    'PL517': 'Walbrzyski',
    'PL518': 'Wroclawski',
    'PL52': 'Opolskie',
    'PL523': 'Nyski',
    'PL524': 'Opolski',
    'PL6': 'Makroregion Pólnocny',
    'PL61': 'Kujawsko-Pomorskie',
    'PL613': 'Bydgosko-Torunski',
    'PL616': 'Grudziadzki',
    'PL617': 'Inowroclawski',
    'PL618': 'Swiecki',
    'PL619': 'Wloclawski',
    'PL62': 'Warminsko-Mazurskie',
    'PL621': 'Elblaski',
    'PL622': 'Olsztynski',
    'PL623': 'Elcki',
    'PL63': 'Pomorskie',
    'PL633': 'Trojmiejski',
    'PL634': 'Gdanski',
    'PL636': 'Slupski',
    'PL637': 'Chojnicki',
    'PL638': 'Starogardzki',
    'PL7': 'Makroregion Centralny',
    'PL71': 'Lódzkie',
    'PL711': 'Miasto Lódz',
    'PL712': 'Lódzki',
    'PL713': 'Piotrkowski',
    'PL714': 'Sieradzki',
    'PL715': 'Skierniewicki',
    'PL72': 'Swietokrzyskie',
    'PL721': 'Kielecki',
    'PL722': 'Sandomiersko-jedrzejowski',
    'PL8': 'Makroregion Wschodni',
    'PL81': 'Lubelskie',
    'PL811': 'Bialski',
    'PL812': 'Chelmsko-zamojski',
    'PL814': 'Lubelski',
    'PL815': 'Pulawski',
    'PL82': 'Podkarpackie',
    'PL821': 'Krosnienski',
    'PL822': 'Przemyski',
    'PL823': 'Rzeszowski',
    'PL824': 'Tarnobrzeski',
    'PL84': 'Podlaskie',
    'PL841': 'Bialostocki',
    'PL842': 'Lomzynski',
    'PL843': 'Suwalski',
    'PL9': 'Makroregion Województwo Mazowieckie',
    'PL91': 'Warszawski stoleczny',
    'PL911': 'Miasto Warszawa',
    'PL912': 'Warszawski wschodni',
    'PL913': 'Warszawski zachodni',
    'PL92': 'Mazowiecki regionalny',
    'PL921': 'Radomski',
    'PL922': 'Ciechanowski',
    'PL923': 'Plocki',
    'PL924': 'Ostrolecki',
    'PL925': 'Siedlecki',
    'PL926': 'Zyrardowski',
    'PT': 'Portugal',
    'PT1': 'Continente',
    'PT11': 'Norte',
    'PT111': 'Alto Minho',
    'PT112': 'Cávado',
    'PT119': 'Ave',
    'PT11A': 'Área Metropolitana do Porto',
    'PT11B': 'Alto Tâmega',
    'PT11C': 'Tâmega e Sousa',
    'PT11D': 'Douro',
    'PT11E': 'Terras de Trás-os-Montes',
    'PT15': 'Algarve',
    'PT150': 'Algarve',
    'PT16': 'Centro (PT)',
    'PT16B': 'Oeste',
    'PT16D': 'Região de Aveiro',
    'PT16E': 'Região de Coimbra',
    'PT16F': 'Região de Leiria',
    'PT16G': 'Viseu Dão Lafões',
    'PT16H': 'Beira Baixa',
    'PT16I': 'Médio Tejo',
    'PT16J': 'Beiras e Serra da Estrela',
    'PT17': 'Área Metropolitana de Lisboa',
    'PT170': 'Área Metropolitana de Lisboa',
    'PT18': 'Alentejo',
    'PT181': 'Alentejo Litoral',
    'PT184': 'Baixo Alentejo',
    'PT185': 'Lezíria do Tejo',
    'PT186': 'Alto Alentejo',
    'PT187': 'Alentejo Central',
    'PT2': 'Região Autónoma dos Açores (PT)',
    'PT20': 'Região Autónoma dos Açores (PT)',
    'PT200': 'Região Autónoma dos Açores (PT)',
    'PT3': 'Região Autónoma da Madeira (PT)',
    'PT30': 'Região Autónoma da Madeira (PT)',
    'PT300': 'Região Autónoma da Madeira (PT)',
    'RO': 'Romania',
    'RO1': 'Macroregiunea unu',
    'RO11': 'Nord-Vest',
    'RO111': 'Bihor',
    'RO112': 'Bistrita-Nasaud',
    'RO113': 'Cluj',
    'RO114': 'Maramures',
    'RO115': 'Satu Mare',
    'RO116': 'Salaj',
    'RO12': 'Centru',
    'RO121': 'Alba',
    'RO122': 'Brasov',
    'RO123': 'Covasna',
    'RO124': 'Harghita',
    'RO125': 'Mures',
    'RO126': 'Sibiu',
    'RO2': 'Macroregiunea doi',
    'RO21': 'Nord-Est',
    'RO211': 'Bacau',
    'RO212': 'Botosani',
    'RO213': 'Iasi',
    'RO214': 'Neamt',
    'RO215': 'Suceava',
    'RO216': 'Vaslui',
    'RO22': 'Sud-Est',
    'RO221': 'Braila',
    'RO222': 'Buzau',
    'RO223': 'Constanta',
    'RO224': 'Galati',
    'RO225': 'Tulcea',
    'RO226': 'Vrancea',
    'RO3': 'Macroregiunea trei',
    'RO31': 'Sud - Muntenia',
    'RO311': 'Arges',
    'RO312': 'Calarasi',
    'RO313': 'Dâmbovita',
    'RO314': 'Giurgiu',
    'RO315': 'Ialomita',
    'RO316': 'Prahova',
    'RO317': 'Teleorman',
    'RO32': 'Bucuresti - Ilfov',
    'RO321': 'Bucuresti',
    'RO322': 'Ilfov',
    'RO4': 'Macroregiunea patru',
    'RO41': 'Sud-Vest Oltenia',
    'RO411': 'Dolj',
    'RO412': 'Gorj',
    'RO413': 'Mehedinti',
    'RO414': 'Olt',
    'RO415': 'Vâlcea',
    'RO42': 'Vest',
    'RO421': 'Arad',
    'RO422': 'Caras-Severin',
    'RO423': 'Hunedoara',
    'RO424': 'Timis',
    'SI': 'Slovenia',
    'SI0': 'Slovenija',
    'SK': 'Slovakia',
    'SK0': 'Slovensko',
    'SK01': 'Bratislavský kraj',
    'SK010': 'Bratislavský kraj',
    'SK02': 'Západné Slovensko',
    'SK021': 'Trnavský kraj',
    'SK022': 'Trenciansky kraj',
    'SK023': 'Nitriansky kraj',
    'SK03': 'Stredné Slovensko',
    'SK031': 'Zilinský kraj',
    'SK032': 'Banskobystrický kraj',
    'SK04': 'Východné Slovensko',
    'SK041': 'Presovský kraj',
    'SK042': 'Kosický kraj',
    'FI': 'Finland',
    'FI1': 'Manner-Suomi',
    'FI19': 'Länsi-Suomi',
    'FI193': 'Keski-Suomi',
    'FI194': 'Etelä-Pohjanmaa',
    'FI195': 'Pohjanmaa',
    'FI196': 'Satakunta',
    'FI197': 'Pirkanmaa',
    'FI1B': 'Helsinki-Uusimaa',
    'FI1B1': 'Helsinki-Uusimaa',
    'FI1C': 'Etelä-Suomi',
    'FI1C1': 'Varsinais-Suomi',
    'FI1C2': 'Kanta-Häme',
    'FI1C3': 'Päijät-Häme',
    'FI1C4': 'Kymenlaakso',
    'FI1C5': 'Etelä-Karjala',
    'FI1D': 'Pohjois- ja Itä-Suomi',
    'FI1D1': 'Etelä-Savo',
    'FI1D2': 'Pohjois-Savo',
    'FI1D3': 'Pohjois-Karjala',
    'FI1D5': 'Keski-Pohjanmaa',
    'FI1D7': 'Lappi',
    'FI1D8': 'Kainuu',
    'FI1D9': 'Pohjois-Pohjanmaa',
    'FI2': 'Åland',
    'FI20': 'Åland',
    'FI200': 'Åland',
    'SE': 'Sweden',
    'SE1': 'Östra Sverige',
    'SE11': 'Stockholm',
    'SE110': 'Stockholms län',
    'SE12': 'Östra Mellansverige',
    'SE121': 'Uppsala län',
    'SE122': 'Södermanlands län',
    'SE123': 'Östergötlands län',
    'SE124': 'Örebro län',
    'SE125': 'Västmanlands län',
    'SE2': 'Södra Sverige',
    'SE21': 'Småland med öarna',
    'SE211': 'Jönköpings län',
    'SE212': 'Kronobergs län',
    'SE213': 'Kalmar län',
    'SE214': 'Gotlands län',
    'SE22': 'Sydsverige',
    'SE221': 'Blekinge län',
    'SE224': 'Skåne län',
    'SE23': 'Västsverige',
    'SE231': 'Hallands län',
    'SE232': 'Västra Götalands län',
    'SE3': 'Norra Sverige',
    'SE31': 'Norra Mellansverige',
    'SE311': 'Värmlands län',
    'SE312': 'Dalarnas län',
    'SE313': 'Gävleborgs län',
    'SE32': 'Mellersta Norrland',
    'SE321': 'Västernorrlands län',
    'SE322': 'Jämtlands län',
    'SE33': 'Övre Norrland',
    'SE331': 'Västerbottens län',
    'SE332': 'Norrbottens län',
    'IS': 'Iceland',
    'IS0': 'Ísland',
    'IS00': 'Ísland',
    'IS001': 'Höfudborgarsvædi',
    'IS002': 'Landsbyggd',
    'LI': 'Liechtenstein',
    'LI0': 'Liechtenstein',
    'LI00': 'Liechtenstein',
    'LI000': 'Liechtenstein',
    'NO': 'Norway',
    'NO0': 'Norge',
    'NO01': 'Oslo og Akershus (statistical region 2016)',
    'NO011': 'Oslo (statistical region 2016)',
    'NO012': 'Akershus (statistical region 2016)',
    'NO02': 'Innlandet',
    'NO021': 'Hedmark (statistical region 2016)',
    'NO022': 'Oppland (statistical region 2016)',
    'NO03': 'Sør-Østlandet (statistical region 2016)',
    'NO031': 'Østfold (statistical region 2016)',
    'NO032': 'Buskerud (statistical region 2016)',
    'NO033': 'Vestfold (statistical region 2016)',
    'NO034': 'Telemark (statistical region 2016)',
    'NO04': 'Agder og Rogaland (statistical region 2016)',
    'NO041': 'Aust-Agder (statistical region 2016)',
    'NO042': 'Vest-Agder (statistical region 2016)',
    'NO043': 'Rogaland (statistical region 2016)',
    'NO05': 'Vestlandet (statistical region 2016)',
    'NO051': 'Hordaland (statistical region 2016)',
    'NO052': 'Sogn og Fjordane (statistical region 2016)',
    'NO053': 'Møre og Romsdal (statistical region 2016)',
    'NO06': 'Trøndelag',
    'NO060': 'Trøndelag',
    'NO061': 'Sør-Trøndelag (statistical region 2016)',
    'NO062': 'Nord-Trøndelag (statistical region 2016)',
    'NO07': 'Nord-Norge',
    'NO071': 'Nordland',
    'NO072': 'Troms (statistical region 2016)',
    'NO073': 'Finnmark (statistical region 2016)',
    'CH': 'Switzerland',
    'CH0': 'Schweiz/Suisse/Svizzera',
    'CH01': 'Région lémanique',
    'CH011': 'Vaud',
    'CH012': 'Valais',
    'CH013': 'Genève',
    'CH02': 'Espace Mittelland',
    'CH021': 'Bern',
    'CH022': 'Freiburg',
    'CH023': 'Solothurn',
    'CH024': 'Neuchâtel',
    'CH025': 'Jura',
    'CH03': 'Nordwestschweiz',
    'CH031': 'Basel-Stadt',
    'CH032': 'Basel-Landschaft',
    'CH033': 'Aargau',
    'CH04': 'Zürich',
    'CH040': 'Zürich',
    'CH05': 'Ostschweiz',
    'CH051': 'Glarus',
    'CH052': 'Schaffhausen',
    'CH053': 'Appenzell Ausserrhoden',
    'CH054': 'Appenzell Innerrhoden',
    'CH055': 'St. Gallen',
    'CH056': 'Graubünden',
    'CH057': 'Thurgau',
    'CH06': 'Zentralschweiz',
    'CH061': 'Luzern',
    'CH062': 'Uri',
    'CH063': 'Schwyz',
    'CH064': 'Obwalden',
    'CH065': 'Nidwalden',
    'CH066': 'Zug',
    'CH07': 'Ticino',
    'CH070': 'Ticino',
    'UK': 'United Kingdom',
    'UKC': 'North East (UK)',
    'UKC1': 'Tees Valley and Durham',
    'UKC11': 'Hartlepool and Stockton-on-Tees',
    'UKC12': 'South Teesside',
    'UKC13': 'Darlington',
    'UKC14': 'Durham CC',
    'UKC2': 'Northumberland and Tyne and Wear',
    'UKC21': 'Northumberland',
    'UKC22': 'Tyneside',
    'UKC23': 'Sunderland',
    'UKD': 'North West (UK)',
    'UKD1': 'Cumbria',
    'UKD11': 'West Cumbria',
    'UKD12': 'East Cumbria',
    'UKD3': 'Greater Manchester',
    'UKD33': 'Manchester',
    'UKD34': 'Greater Manchester South West',
    'UKD35': 'Greater Manchester South East',
    'UKD36': 'Greater Manchester North West',
    'UKD37': 'Greater Manchester North East',
    'UKD4': 'Lancashire',
    'UKD41': 'Blackburn with Darwen',
    'UKD42': 'Blackpool',
    'UKD44': 'Lancaster & Wyre',
    'UKD45': 'Mid Lancashire',
    'UKD46': 'East Lancashire',
    'UKD47': 'Chorley & West Lancashire',
    'UKD6': 'Cheshire',
    'UKD61': 'Warrington',
    'UKD62': 'Cheshire East',
    'UKD63': 'Cheshire West and Chester',
    'UKD7': 'Merseyside',
    'UKD71': 'East Merseyside',
    'UKD72': 'Liverpool',
    'UKD73': 'Sefton',
    'UKD74': 'Wirral',
    'UKE': 'Yorkshire and The Humber',
    'UKE1': 'East Yorkshire and Northern Lincolnshire',
    'UKE11': 'Kingston upon Hull, City of',
    'UKE12': 'East Riding of Yorkshire',
    'UKE13': 'North and North East Lincolnshire',
    'UKE2': 'North Yorkshire',
    'UKE21': 'York',
    'UKE22': 'North Yorkshire CC',
    'UKE3': 'South Yorkshire',
    'UKE31': 'Barnsley, Doncaster and Rotherham',
    'UKE32': 'Sheffield',
    'UKE4': 'West Yorkshire',
    'UKE41': 'Bradford',
    'UKE42': 'Leeds',
    'UKE44': 'Calderdale and Kirklees',
    'UKE45': 'Wakefield',
    'UKF': 'East Midlands (UK)',
    'UKF1': 'Derbyshire and Nottinghamshire',
    'UKF11': 'Derby',
    'UKF12': 'East Derbyshire',
    'UKF13': 'South and West Derbyshire',
    'UKF14': 'Nottingham',
    'UKF15': 'North Nottinghamshire',
    'UKF16': 'South Nottinghamshire',
    'UKF2': 'Leicestershire, Rutland and Northamptonshire',
    'UKF21': 'Leicester',
    'UKF22': 'Leicestershire CC and Rutland',
    'UKF24': 'West Northamptonshire',
    'UKF25': 'North Northamptonshire',
    'UKF3': 'Lincolnshire',
    'UKF30': 'Lincolnshire',
    'UKG': 'West Midlands (UK)',
    'UKG1': 'Herefordshire, Worcestershire and Warwickshire',
    'UKG11': 'Herefordshire, County of',
    'UKG12': 'Worcestershire',
    'UKG13': 'Warwickshire',
    'UKG2': 'Shropshire and Staffordshire',
    'UKG21': 'Telford and Wrekin',
    'UKG22': 'Shropshire CC',
    'UKG23': 'Stoke-on-Trent',
    'UKG24': 'Staffordshire CC',
    'UKG3': 'West Midlands',
    'UKG31': 'Birmingham',
    'UKG32': 'Solihull',
    'UKG33': 'Coventry',
    'UKG36': 'Dudley',
    'UKG37': 'Sandwell',
    'UKG38': 'Walsall',
    'UKG39': 'Wolverhampton',
    'UKH': 'East of England',
    'UKH1': 'East Anglia',
    'UKH11': 'Peterborough',
    'UKH12': 'Cambridgeshire CC',
    'UKH14': 'Suffolk',
    'UKH15': 'Norwich & East Norfolk',
    'UKH16': 'North & West Norfolk',
    'UKH17': 'Breckland & South Norfolk',
    'UKH2': 'Bedfordshire and Hertfordshire',
    'UKH21': 'Luton',
    'UKH23': 'Hertfordshire',
    'UKH24': 'Bedford',
    'UKH25': 'Central Bedfordshire',
    'UKH3': 'Essex',
    'UKH31': 'Southend-on-Sea',
    'UKH32': 'Thurrock',
    'UKH34': 'Essex Haven Gateway',
    'UKH35': 'West Essex',
    'UKH36': 'Heart of Essex',
    'UKH37': 'Essex Thames Gateway',
    'UKI': 'London',
    'UKI3': 'Inner London - West',
    'UKI31': 'Camden & City of London',
    'UKI32': 'Westminster',
    'UKI33': 'Kensington and Chelsea & Hammersmith and Fulham',
    'UKI34': 'Wandsworth',
    'UKI4': 'Inner London - East',
    'UKI41': 'Hackney & Newham',
    'UKI42': 'Tower Hamlets',
    'UKI43': 'Haringey & Islington',
    'UKI44': 'Lewisham & Southwark',
    'UKI45': 'Lambeth',
    'UKI5': 'Outer London - East and North East',
    'UKI51': 'Bexley & Greenwich',
    'UKI52': 'Barking & Dagenham and Havering',
    'UKI53': 'Redbridge & Waltham Forest',
    'UKI54': 'Enfield',
    'UKI6': 'Outer London - South',
    'UKI61': 'Bromley',
    'UKI62': 'Croydon',
    'UKI63': 'Merton, Kingston upon Thames & Sutton',
    'UKI7': 'Outer London - West and North West',
    'UKI71': 'Barnet',
    'UKI72': 'Brent',
    'UKI73': 'Ealing',
    'UKI74': 'Harrow & Hillingdon',
    'UKI75': 'Hounslow & Richmond upon Thames',
    'UKJ': 'South East (UK)',
    'UKJ1': 'Berkshire, Buckinghamshire and Oxfordshire',
    'UKJ11': 'Berkshire',
    'UKJ12': 'Milton Keynes',
    'UKJ13': 'Buckinghamshire CC',
    'UKJ14': 'Oxfordshire',
    'UKJ2': 'Surrey, East and West Sussex',
    'UKJ21': 'Brighton and Hove',
    'UKJ22': 'East Sussex CC',
    'UKJ25': 'West Surrey',
    'UKJ26': 'East Surrey',
    'UKJ27': 'West Sussex (South West)',
    'UKJ28': 'West Sussex (North East)',
    'UKJ3': 'Hampshire and Isle of Wight',
    'UKJ31': 'Portsmouth',
    'UKJ32': 'Southampton',
    'UKJ34': 'Isle of Wight',
    'UKJ35': 'South Hampshire',
    'UKJ36': 'Central Hampshire',
    'UKJ37': 'North Hampshire',
    'UKJ4': 'Kent',
    'UKJ41': 'Medway',
    'UKJ43': 'Kent Thames Gateway',
    'UKJ44': 'East Kent',
    'UKJ45': 'Mid Kent',
    'UKJ46': 'West Kent',
    'UKK': 'South West (UK)',
    'UKK1': 'Gloucestershire, Wiltshire and Bristol/Bath area',
    'UKK11': 'Bristol, City of',
    'UKK12': 'Bath and North East Somerset, North Somerset and South Gloucestershire',
    'UKK13': 'Gloucestershire',
    'UKK14': 'Swindon',
    'UKK15': 'Wiltshire CC',
    'UKK2': 'Dorset and Somerset',
    'UKK21': 'Bournemouth and Poole (NUTS 2016)',
    'UKK22': 'Dorset CC (NUTS 2016)',
    'UKK23': 'Somerset',
    'UKK3': 'Cornwall and Isles of Scilly',
    'UKK30': 'Cornwall and Isles of Scilly',
    'UKK4': 'Devon',
    'UKK41': 'Plymouth',
    'UKK42': 'Torbay',
    'UKK43': 'Devon CC',
    'UKL': 'Wales',
    'UKL1': 'West Wales and The Valleys',
    'UKL11': 'Isle of Anglesey',
    'UKL12': 'Gwynedd',
    'UKL13': 'Conwy and Denbighshire',
    'UKL14': 'South West Wales',
    'UKL15': 'Central Valleys',
    'UKL16': 'Gwent Valleys',
    'UKL17': 'Bridgend and Neath Port Talbot',
    'UKL18': 'Swansea',
    'UKL2': 'East Wales',
    'UKL21': 'Monmouthshire and Newport',
    'UKL22': 'Cardiff and Vale of Glamorgan',
    'UKL23': 'Flintshire and Wrexham',
    'UKL24': 'Powys',
    'UKM': 'Scotland',
    'UKM5': 'North Eastern Scotland',
    'UKM50': 'Aberdeen City and Aberdeenshire',
    'UKM6': 'Highlands and Islands',
    'UKM61': 'Caithness & Sutherland and Ross & Cromarty',
    'UKM62': 'Inverness & Nairn and Moray, Badenoch & Strathspey',
    'UKM63': 'Lochaber, Skye & Lochalsh, Arran & Cumbrae and Argyll & Bute',
    'UKM64': 'Eilean Siar (Western Isles)',
    'UKM65': 'Orkney Islands',
    'UKM66': 'Shetland Islands',
    'UKM7': 'Eastern Scotland',
    'UKM71': 'Angus and Dundee City',
    'UKM72': 'Clackmannanshire and Fife',
    'UKM73': 'East Lothian and Midlothian',
    'UKM75': 'Edinburgh, City of',
    'UKM76': 'Falkirk',
    'UKM77': 'Perth & Kinross and Stirling',
    'UKM78': 'West Lothian',
    'UKM8': 'West Central Scotland',
    'UKM81': 'East Dunbartonshire, West Dunbartonshire and Helensburgh & Lomond',
    'UKM82': 'Glasgow City',
    'UKM83': 'Inverclyde, East Renfrewshire and Renfrewshire',
    'UKM84': 'North Lanarkshire',
    'UKM9': 'Southern Scotland',
    'UKM91': 'Scottish Borders',
    'UKM92': 'Dumfries & Galloway',
    'UKM93': 'East Ayrshire and North Ayrshire mainland',
    'UKM94': 'South Ayrshire',
    'UKM95': 'South Lanarkshire',
    'UKN': 'Northern Ireland (UK)',
    'UKN0': 'Northern Ireland (UK)',
    'UKN06': 'Belfast',
    'UKN07': 'Armagh City, Banbridge and Craigavon',
    'UKN08': 'Newry, Mourne and Down',
    'UKN09': 'Ards and North Down',
    'UKN10': 'Derry City and Strabane (NUTS 2016)',
    'UKN11': 'Mid Ulster (NUTS 2016)',
    'UKN12': 'Causeway Coast and Glens (NUTS 2016)',
    'UKN13': 'Antrim and Newtownabbey (NUTS 2016)',
    'UKN14': 'Lisburn and Castlereagh (NUTS 2016)',
    'UKN15': 'Mid and East Antrim (NUTS 2016)',
    'UKN16': 'Fermanagh and Omagh (NUTS 2016)',
    'ME': 'Montenegro',
    'ME0': 'Crna Gora',
    'ME00': 'Crna Gora',
    'ME000': 'Crna Gora',
    'AL': 'Albania',
    'AL0': 'Shqipëria',
    'AL01': 'Veri',
    'AL011': 'Dibër',
    'AL012': 'Durrës',
    'AL013': 'Kukës',
    'AL014': 'Lezhë',
    'AL015': 'Shkodër',
    'AL02': 'Qender',
    'AL021': 'Elbasan',
    'AL022': 'Tiranë',
    'AL03': 'Jug',
    'AL031': 'Berat',
    'AL032': 'Fier',
    'AL033': 'Gjirokastër',
    'AL034': 'Korcë',
    'AL035': 'Vlorë',
    'RS': 'Serbia',
    'RS1': 'Srbija - sever',
    'RS11': 'Beogradski region',
    'RS110': 'Beogradska oblast',
    'RS12': 'Region Vojvodine',
    'RS121': 'Zapadnobacka oblast',
    'RS122': 'Juznobanatska oblast',
    'RS123': 'Juznobacka oblast',
    'RS124': 'Severnobanatska oblast',
    'RS125': 'Severnobacka oblast',
    'RS126': 'Srednjobanatska oblast',
    'RS127': 'Sremska oblast',
    'RS2': 'Srbija - jug',
    'RS21': 'Region Sumadije i Zapadne Srbije',
    'RS211': 'Zlatiborska oblast',
    'RS212': 'Kolubarska oblast',
    'RS213': 'Macvanska oblast',
    'RS214': 'Moravicka oblast',
    'RS215': 'Pomoravska oblast',
    'RS216': 'Rasinska oblast',
    'RS217': 'Raska oblast',
    'RS218': 'Sumadijska oblast',
    'RS22': 'Region Juzne i Istocne Srbije',
    'RS221': 'Borska oblast',
    'RS222': 'Branicevska oblast',
    'RS223': 'Zajecarska oblast',
    'RS224': 'Jablanicka oblast',
    'RS225': 'Nisavska oblast',
    'RS226': 'Pirotska oblast',
    'RS227': 'Podunavska oblast',
    'RS228': 'Pcinjska oblast',
    'RS229': 'Toplicka oblast',
}

UN_LOC_VARS = {
    'Andorra',
    'Albania',
    'Armenia',
    'Austria',
    'Belgium',
    'Bulgaria',
    'Switzerland',
    'Cyprus',
    'Czechia',
    'Germany',
    'Denmark',
    'Estonia',
    'Greece',
    'Spain',
    'Finland',
    'France',
    'Georgia',
    'Croatia',
    'Hungary',
    'Iceland',
    'Italy',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Latvia',
    'Montenegro',
    'Malta',
    'Netherlands',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'Serbia',
    'Sweden',
    'Slovenia',
    'Slovakia',
    'United Kingdom',
}
