BG_MUNICIPALITIES = {
    'ОБЩО': 'Total',
    'Общо за страната': 'Total',
    'Белоградчик': 'Belogradchik',
    'Бойница': 'Boynitsa',
    'Брегово': 'Bregovo',
    'Видин': 'Vidin',
    'Грамада': 'Gramada',
    'Димово': 'Dimovo',
    'Кула': 'Kula',
    'Макреш': 'Makresh',
    'Ново село': 'Novo selo',
    'Ружинци': 'Ruzhintsi',
    'Чупрене': 'Chuprene',
    'Борован': 'Borovan',
    'Бяла Слатина': 'Byala Slatina',
    'Враца': 'Vratsa',
    'Козлодуй': 'Kozloduy',
    'Криводол': 'Krivodol',
    'Мездра': 'Mezdra',
    'Мизия': 'Mizia',
    'Оряхово': 'Oryahovo',
    'Роман': 'Roman',
    'Хайредин': 'Hayredin',
    'Априлци': 'Apriltsi',
    'Летница': 'Letnitsa',
    'Ловеч': 'Lovech',
    'Луковит': 'Lukovit',
    'Тетевен': 'Teteven',
    'Троян': 'Troyan',
    'Угърчин': 'Ugarchin',
    'Ябланица': 'Yablanitsa',
    'Берковица': 'Berkovitsa',
    'Бойчиновци': 'Boychinovtsi',
    'Брусарци': 'Brusartsi',
    'Вълчедръм': 'Valchedram',
    'Вършец': 'Varshets',
    'Георги Дамяново': 'Georgi Damyanovo',
    'Лом': 'Lom',
    'Медковец': 'Medkovets',
    'Монтана': 'Montana',
    'Чипровци': 'Chiprovtsi',
    'Якимово': 'Yakimovo',
    'Белене': 'Belene',
    'Гулянци': 'Gulyantsi',
    'Долна Митрополия': 'Dolna Mitropolia',
    'Долни Дъбник': 'Dolni Dabnik',
    'Искър': 'Iskar',
    'Кнежа': 'Knezha',
    'Левски': 'Levski',
    'Никопол': 'Nikopol',
    'Плевен': 'Pleven',
    'Пордим': 'Pordim',
    'Червен бряг': 'Cherven bryag',
    'Велико Търново': 'Veliko Tarnovo',
    'Горна Оряховица': 'Gorna Oryahovitsa',
    'Елена': 'Elena',
    'Златарица': 'Zlataritsa',
    'Лясковец': 'Lyaskovets',
    'Павликени': 'Pavlikeni',
    'Полски Тръмбеш': 'Polski Trambesh',
    'Свищов': 'Svishtov',
    'Стражица': 'Strazhitsa',
    'Сухиндол': 'Suhindol',
    'Габрово': 'Gabrovo',
    'Дряново': 'Dryanovo',
    'Севлиево': 'Sevlievo',
    'Трявна': 'Tryavna',
    'Завет': 'Zavet',
    'Исперих': 'Isperih',
    'Кубрат': 'Kubrat',
    'Лозница': 'Loznitsa',
    'Разград': 'Razgrad',
    'Самуил': 'Samuil',
    'Цар Калоян': 'Tsar Kaloyan',
    'Борово': 'Borovo',
    'Бяла': 'Byala',
    'Ветово': 'Vetovo',
    'Две могили': 'Dve mogili',
    'Иваново': 'Ivanovo',
    'Русе': 'Ruse',
    'Сливо поле': 'Slivo pole',
    'Ценово': 'Tsenovo',
    'Алфатар': 'Alfatar',
    'Главиница': 'Glavinitsa',
    'Дулово': 'Dulovo',
    'Кайнарджа': 'Kaynardzha',
    'Силистра': 'Silistra',
    'Ситово': 'Sitovo',
    'Тутракан': 'Tutrakan',
    'Аврен': 'Avren',
    'Аксаково': 'Aksakovo',
    'Белослав': 'Beloslav',
    'Варна': 'Varna',
    'Ветрино': 'Vetrino',
    'Вълчи дол': 'Valchi dol',
    'Девня': 'Devnya',
    'Долни чифлик': 'Dolni chiflik',
    'Дългопол': 'Dalgopol',
    'Провадия': 'Provadia',
    'Суворово': 'Suvorovo',
    'Балчик': 'Balchik',
    'Генерал Тошево': 'General Toshevo',
    'Добрич-селска': 'Dobrich-selska',
    'Добрич': 'Dobrich',
    'Каварна': 'Kavarna',
    'Крушари': 'Krushari',
    'Тервел': 'Tervel',
    'Шабла': 'Shabla',
    'Антоново': 'Antonovo',
    'Омуртаг': 'Omurtag',
    'Опака': 'Opaka',
    'Попово': 'Popovo',
    'Търговище': 'Targovishte',
    'Велики Преслав': 'Veliki Preslav',
    'Венец': 'Venets',
    'Върбица': 'Varbitsa',
    'Каолиново': 'Kaolinovo',
    'Каспичан': 'Kaspichan',
    'Никола Козлево': 'Nikola Kozlevo',
    'Нови пазар': 'Novi pazar',
    'Смядово': 'Smyadovo',
    'Хитрино': 'Hitrino',
    'Шумен': 'Shumen',
    'Айтос': 'Aytos',
    'Бургас': 'Burgas',
    'Камено': 'Kameno',
    'Карнобат': 'Karnobat',
    'Малко Търново': 'Malko Tarnovo',
    'Несебър': 'Nesebar',
    'Поморие': 'Pomorie',
    'Приморско': 'Primorsko',
    'Руен': 'Ruen',
    'Созопол': 'Sozopol',
    'Средец': 'Sredets',
    'Сунгурларе': 'Sungurlare',
    'Царево': 'Tsarevo',
    'Котел': 'Kotel',
    'Нова Загора': 'Nova Zagora',
    'Сливен': 'Sliven',
    'Твърдица': 'Tvarditsa',
    'Братя Даскалови': 'Bratya Daskalovi',
    'Гурково': 'Gurkovo',
    'Гълъбово': 'Galabovo',
    'Казанлък': 'Kazanlak',
    'Мъглиж': 'Maglizh',
    'Николаево': 'Nikolaevo',
    'Опан': 'Opan',
    'Павел баня': 'Pavel banya',
    'Раднево': 'Radnevo',
    'Стара Загора': 'Stara Zagora',
    'Чирпан': 'Chirpan',
    'Болярово': 'Bolyarovo',
    'Елхово': 'Elhovo',
    'Стралджа': 'Straldzha',
    'Тунджа': 'Tundzha',
    'Ямбол': 'Yambol',
    'Банско': 'Bansko',
    'Белица': 'Belitsa',
    'Благоевград': 'Blagoevgrad',
    'Гоце Делчев': 'Gotse Delchev',
    'Гърмен': 'Garmen',
    'Кресна': 'Kresna',
    'Петрич': 'Petrich',
    'Разлог': 'Razlog',
    'Сандански': 'Sandanski',
    'Сатовча': 'Satovcha',
    'Симитли': 'Simitli',
    'Струмяни': 'Strumyani',
    'Хаджидимово': 'Hadzhidimovo',
    'Якоруда': 'Yakoruda',
    'Бобов дол': 'Bobov dol',
    'Бобошево': 'Boboshevo',
    'Дупница': 'Dupnitsa',
    'Кочериново': 'Kocherinovo',
    'Кюстендил': 'Kyustendil',
    'Невестино': 'Nevestino',
    'Рила': 'Rila',
    'Сапарева баня': 'Sapareva banya',
    'Трекляно': 'Treklyano',
    'Брезник': 'Breznik',
    'Земен': 'Zemen',
    'Ковачевци': 'Kovachevtsi',
    'Перник': 'Pernik',
    'Радомир': 'Radomir',
    'Трън': 'Tran',
    'Антон': 'Anton',
    'Божурище': 'Bozhurishte',
    'Ботевград': 'Botevgrad',
    'Годеч': 'Godech',
    'Горна Малина': 'Gorna Malina',
    'Долна баня': 'Dolna banya',
    'Драгоман': 'Dragoman',
    'Елин Пелин': 'Elin Pelin',
    'Етрополе': 'Etropole',
    'Златица': 'Zlatitsa',
    'Ихтиман': 'Ihtiman',
    'Копривщица': 'Koprivshtitsa',
    'Костенец': 'Kostenets',
    'Костинброд': 'Kostinbrod',
    'Мирково': 'Mirkovo',
    'Пирдоп': 'Pirdop',
    'Правец': 'Pravets',
    'Самоков': 'Samokov',
    'Своге': 'Svoge',
    'Сливница': 'Slivnitsa',
    'Чавдар': 'Chavdar',
    'Челопеч': 'Chelopech',
    'Столична': 'Sofia',
    'Ардино': 'Ardino',
    'Джебел': 'Dzhebel',
    'Кирково': 'Kirkovo',
    'Крумовград': 'Krumovgrad',
    'Кърджали': 'Kardzhali',
    'Момчилград': 'Momchilgrad',
    'Черноочене': 'Chernoochene',
    'Батак': 'Batak',
    'Белово': 'Belovo',
    'Брацигово': 'Bratsigovo',
    'Велинград': 'Velingrad',
    'Сърница': 'Sarnitsa',
    'Лесичово': 'Lesichovo',
    'Пазарджик': 'Pazardzhik',
    'Панагюрище': 'Panagyurishte',
    'Пещера': 'Peshtera',
    'Ракитово': 'Rakitovo',
    'Септември': 'Septemvri',
    'Стрелча': 'Strelcha',
    'Асеновград': 'Asenovgrad',
    'Брезово': 'Brezovo',
    'Калояново': 'Kaloyanovo',
    'Карлово': 'Karlovo',
    'Кричим': 'Krichim',
    'Куклен': 'Kuklen',
    'Лъки': 'Laki',
    'Марица': 'Maritsa',
    'Перущица': 'Perushtitsa',
    'Пловдив': 'Plovdiv',
    'Първомай': 'Parvomay',
    'Раковски': 'Rakovski',
    'Родопи': 'Rodopi',
    'Садово': 'Sadovo',
    'Сопот': 'Sopot',
    'Стамболийски': 'Stamboliyski',
    'Съединение': 'Saedinenie',
    'Хисаря': 'Hisarya',
    'Баните': 'Banite',
    'Борино': 'Borino',
    'Девин': 'Devin',
    'Доспат': 'Dospat',
    'Златоград': 'Zlatograd',
    'Мадан': 'Madan',
    'Неделино': 'Nedelino',
    'Рудозем': 'Rudozem',
    'Смолян': 'Smolyan',
    'Чепеларе': 'Chepelare',
    'Димитровград': 'Dimitrovgrad',
    'Ивайловград': 'Ivaylovgrad',
    'Любимец': 'Lyubimets',
    'Маджарово': 'Madzharovo',
    'Минерални бани': 'Mineralni bani',
    'Свиленград': 'Svilengrad',
    'Симеоновград': 'Simeonovgrad',
    'Стамболово': 'Stambolovo',
    'Тополовград': 'Topolovgrad',
    'Харманли': 'Harmanli',
    'Хасково': 'Haskovo',
}

DECODE_REGION = {
    'Total': 'Total',
    'Belogradchik': 'Vidin',
    'Boynitsa': 'Vidin',
    'Bregovo': 'Vidin',
    'Vidin': 'Vidin',
    'Gramada': 'Vidin',
    'Dimovo': 'Vidin',
    'Kula': 'Vidin',
    'Makresh': 'Vidin',
    'Novo selo': 'Vidin',
    'Ruzhintsi': 'Vidin',
    'Chuprene': 'Vidin',
    'Borovan': 'Vratsa',
    'Byala Slatina': 'Vratsa',
    'Vratsa': 'Vratsa',
    'Kozloduy': 'Vratsa',
    'Krivodol': 'Vratsa',
    'Mezdra': 'Vratsa',
    'Mizia': 'Vratsa',
    'Oryahovo': 'Vratsa',
    'Roman': 'Vratsa',
    'Hayredin': 'Vratsa',
    'Apriltsi': 'Lovech',
    'Letnitsa': 'Lovech',
    'Lovech': 'Lovech',
    'Lukovit': 'Lovech',
    'Teteven': 'Lovech',
    'Troyan': 'Lovech',
    'Ugarchin': 'Lovech',
    'Yablanitsa': 'Lovech',
    'Berkovitsa': 'Montana',
    'Boychinovtsi': 'Montana',
    'Brusartsi': 'Montana',
    'Valchedram': 'Montana',
    'Varshets': 'Montana',
    'Georgi Damyanovo': 'Montana',
    'Lom': 'Montana',
    'Medkovets': 'Montana',
    'Montana': 'Montana',
    'Chiprovtsi': 'Montana',
    'Yakimovo': 'Montana',
    'Belene': 'Pleven',
    'Gulyantsi': 'Pleven',
    'Dolna Mitropolia': 'Pleven',
    'Dolni Dabnik': 'Pleven',
    'Iskar': 'Pleven',
    'Knezha': 'Pleven',
    'Levski': 'Pleven',
    'Nikopol': 'Pleven',
    'Pleven': 'Pleven',
    'Pordim': 'Pleven',
    'Cherven bryag': 'Pleven',
    'Veliko Tarnovo': 'Veliko Tarnovo',
    'Gorna Oryahovitsa': 'Veliko Tarnovo',
    'Elena': 'Veliko Tarnovo',
    'Zlataritsa': 'Veliko Tarnovo',
    'Lyaskovets': 'Veliko Tarnovo',
    'Pavlikeni': 'Veliko Tarnovo',
    'Polski Trambesh': 'Veliko Tarnovo',
    'Svishtov': 'Veliko Tarnovo',
    'Strazhitsa': 'Veliko Tarnovo',
    'Suhindol': 'Veliko Tarnovo',
    'Gabrovo': 'Gabrovo',
    'Dryanovo': 'Gabrovo',
    'Sevlievo': 'Gabrovo',
    'Tryavna': 'Gabrovo',
    'Zavet': 'Razgrad',
    'Isperih': 'Razgrad',
    'Kubrat': 'Razgrad',
    'Loznitsa': 'Razgrad',
    'Razgrad': 'Razgrad',
    'Samuil': 'Razgrad',
    'Tsar Kaloyan': 'Razgrad',
    'Borovo': 'Ruse',
    'Vetovo': 'Ruse',
    'Dve mogili': 'Ruse',
    'Ivanovo': 'Ruse',
    'Ruse': 'Ruse',
    'Slivo pole': 'Ruse',
    'Tsenovo': 'Ruse',
    'Alfatar': 'Silistra',
    'Glavinitsa': 'Silistra',
    'Dulovo': 'Silistra',
    'Kaynardzha': 'Silistra',
    'Silistra': 'Silistra',
    'Sitovo': 'Silistra',
    'Tutrakan': 'Silistra',
    'Avren': 'Varna',
    'Aksakovo': 'Varna',
    'Beloslav': 'Varna',
    'Varna': 'Varna',
    'Vetrino': 'Varna',
    'Valchi dol': 'Varna',
    'Devnya': 'Varna',
    'Dolni chiflik': 'Varna',
    'Dalgopol': 'Varna',
    'Provadia': 'Varna',
    'Suvorovo': 'Varna',
    'Balchik': 'Dobrich',
    'General Toshevo': 'Dobrich',
    'Dobrich-selska': 'Dobrich',
    'Dobrich': 'Dobrich',
    'Kavarna': 'Dobrich',
    'Krushari': 'Dobrich',
    'Tervel': 'Dobrich',
    'Shabla': 'Dobrich',
    'Antonovo': 'Targovishte',
    'Omurtag': 'Targovishte',
    'Opaka': 'Targovishte',
    'Popovo': 'Targovishte',
    'Targovishte': 'Targovishte',
    'Veliki Preslav': 'Shumen',
    'Venets': 'Shumen',
    'Varbitsa': 'Shumen',
    'Kaolinovo': 'Shumen',
    'Kaspichan': 'Shumen',
    'Nikola Kozlevo': 'Shumen',
    'Novi pazar': 'Shumen',
    'Smyadovo': 'Shumen',
    'Hitrino': 'Shumen',
    'Shumen': 'Shumen',
    'Aytos': 'Burgas',
    'Burgas': 'Burgas',
    'Kameno': 'Burgas',
    'Karnobat': 'Burgas',
    'Malko Tarnovo': 'Burgas',
    'Nesebar': 'Burgas',
    'Pomorie': 'Burgas',
    'Primorsko': 'Burgas',
    'Ruen': 'Burgas',
    'Sozopol': 'Burgas',
    'Sredets': 'Burgas',
    'Sungurlare': 'Burgas',
    'Tsarevo': 'Burgas',
    'Kotel': 'Sliven',
    'Nova Zagora': 'Sliven',
    'Sliven': 'Sliven',
    'Tvarditsa': 'Sliven',
    'Bratya Daskalovi': 'Stara Zagora',
    'Gurkovo': 'Stara Zagora',
    'Galabovo': 'Stara Zagora',
    'Kazanlak': 'Stara Zagora',
    'Maglizh': 'Stara Zagora',
    'Nikolaevo': 'Stara Zagora',
    'Opan': 'Stara Zagora',
    'Pavel banya': 'Stara Zagora',
    'Radnevo': 'Stara Zagora',
    'Stara Zagora': 'Stara Zagora',
    'Chirpan': 'Stara Zagora',
    'Bolyarovo': 'Yambol',
    'Elhovo': 'Yambol',
    'Straldzha': 'Yambol',
    'Tundzha': 'Yambol',
    'Yambol': 'Yambol',
    'Bansko': 'Blagoevgrad',
    'Belitsa': 'Blagoevgrad',
    'Blagoevgrad': 'Blagoevgrad',
    'Gotse Delchev': 'Blagoevgrad',
    'Garmen': 'Blagoevgrad',
    'Kresna': 'Blagoevgrad',
    'Petrich': 'Blagoevgrad',
    'Razlog': 'Blagoevgrad',
    'Sandanski': 'Blagoevgrad',
    'Satovcha': 'Blagoevgrad',
    'Simitli': 'Blagoevgrad',
    'Strumyani': 'Blagoevgrad',
    'Hadzhidimovo': 'Blagoevgrad',
    'Yakoruda': 'Blagoevgrad',
    'Bobov dol': 'Kyustendil',
    'Boboshevo': 'Kyustendil',
    'Dupnitsa': 'Kyustendil',
    'Kocherinovo': 'Kyustendil',
    'Kyustendil': 'Kyustendil',
    'Nevestino': 'Kyustendil',
    'Rila': 'Kyustendil',
    'Sapareva banya': 'Kyustendil',
    'Treklyano': 'Kyustendil',
    'Breznik': 'Pernik',
    'Zemen': 'Pernik',
    'Kovachevtsi': 'Pernik',
    'Pernik': 'Pernik',
    'Radomir': 'Pernik',
    'Tran': 'Pernik',
    'Anton': 'Sofia',
    'Bozhurishte': 'Sofia',
    'Botevgrad': 'Sofia',
    'Godech': 'Sofia',
    'Gorna Malina': 'Sofia',
    'Dolna banya': 'Sofia',
    'Dragoman': 'Sofia',
    'Elin Pelin': 'Sofia',
    'Etropole': 'Sofia',
    'Zlatitsa': 'Sofia',
    'Ihtiman': 'Sofia',
    'Koprivshtitsa': 'Sofia',
    'Kostenets': 'Sofia',
    'Kostinbrod': 'Sofia',
    'Mirkovo': 'Sofia',
    'Pirdop': 'Sofia',
    'Pravets': 'Sofia',
    'Samokov': 'Sofia',
    'Svoge': 'Sofia',
    'Slivnitsa': 'Sofia',
    'Chavdar': 'Sofia',
    'Chelopech': 'Sofia',
    'Sofia': 'Sofia (stolitsa)',
    'Ardino': 'Kardzhali',
    'Dzhebel': 'Kardzhali',
    'Kirkovo': 'Kardzhali',
    'Krumovgrad': 'Kardzhali',
    'Kardzhali': 'Kardzhali',
    'Momchilgrad': 'Kardzhali',
    'Chernoochene': 'Kardzhali',
    'Batak': 'Pazardzhik',
    'Belovo': 'Pazardzhik',
    'Bratsigovo': 'Pazardzhik',
    'Velingrad': 'Pazardzhik',
    'Sarnitsa': 'Pazardzhik',
    'Lesichovo': 'Pazardzhik',
    'Pazardzhik': 'Pazardzhik',
    'Panagyurishte': 'Pazardzhik',
    'Peshtera': 'Pazardzhik',
    'Rakitovo': 'Pazardzhik',
    'Septemvri': 'Pazardzhik',
    'Strelcha': 'Pazardzhik',
    'Asenovgrad': 'Plovdiv',
    'Brezovo': 'Plovdiv',
    'Kaloyanovo': 'Plovdiv',
    'Karlovo': 'Plovdiv',
    'Krichim': 'Plovdiv',
    'Kuklen': 'Plovdiv',
    'Laki': 'Plovdiv',
    'Maritsa': 'Plovdiv',
    'Perushtitsa': 'Plovdiv',
    'Plovdiv': 'Plovdiv',
    'Parvomay': 'Plovdiv',
    'Rakovski': 'Plovdiv',
    'Rodopi': 'Plovdiv',
    'Sadovo': 'Plovdiv',
    'Sopot': 'Plovdiv',
    'Stamboliyski': 'Plovdiv',
    'Saedinenie': 'Plovdiv',
    'Hisarya': 'Plovdiv',
    'Banite': 'Smolyan',
    'Borino': 'Smolyan',
    'Devin': 'Smolyan',
    'Dospat': 'Smolyan',
    'Zlatograd': 'Smolyan',
    'Madan': 'Smolyan',
    'Nedelino': 'Smolyan',
    'Rudozem': 'Smolyan',
    'Smolyan': 'Smolyan',
    'Chepelare': 'Smolyan',
    'Dimitrovgrad': 'Haskovo',
    'Ivaylovgrad': 'Haskovo',
    'Lyubimets': 'Haskovo',
    'Madzharovo': 'Haskovo',
    'Mineralni bani': 'Haskovo',
    'Svilengrad': 'Haskovo',
    'Simeonovgrad': 'Haskovo',
    'Stambolovo': 'Haskovo',
    'Topolovgrad': 'Haskovo',
    'Harmanli': 'Haskovo',
    'Haskovo': 'Haskovo',
}
