BY_REGION_FILT_COLS = ['Дата',
                       'BLG_ALL', 'BGS_ALL', 'VAR_ALL', 'VTR_ALL', 'VID_ALL', 'VRC_ALL', 'GAB_ALL', 'DOB_ALL',
                       'KRZ_ALL', 'KNL_ALL', 'LOV_ALL', 'MON_ALL', 'PAZ_ALL', 'PER_ALL', 'PVN_ALL', 'PDV_ALL',
                       'RAZ_ALL', 'RSE_ALL', 'SLS_ALL', 'SLV_ALL', 'SML_ALL', 'SFO_ALL', 'SOF_ALL', 'SZR_ALL',
                       'TGV_ALL', 'HKV_ALL', 'SHU_ALL', 'JAM_ALL']

BY_REGION_DECODE_COLUMNS = {
    'Дата': 'Date',
    'BLG_ALL': 'Blagoevgrad',
    'BGS_ALL': 'Burgas',
    'VAR_ALL': 'Varna',
    'VTR_ALL': 'Veliko Tarnovo',
    'VID_ALL': 'Vidin',
    'VRC_ALL': 'Vratsa',
    'GAB_ALL': 'Gabrovo',
    'DOB_ALL': 'Dobrich',
    'KRZ_ALL': 'Kardzhali',
    'KNL_ALL': 'Kyustendil',
    'LOV_ALL': 'Lovech',
    'MON_ALL': 'Montana',
    'PAZ_ALL': 'Pazardzhik',
    'PER_ALL': 'Pernik',
    'PVN_ALL': 'Pleven',
    'PDV_ALL': 'Plovdiv',
    'RAZ_ALL': 'Razgrad',
    'RSE_ALL': 'Ruse',
    'SLS_ALL': 'Silistra',
    'SLV_ALL': 'Sliven',
    'SML_ALL': 'Smolyan',
    'SFO_ALL': 'Sofia',
    'SOF_ALL': 'Sofia (stolitsa)',
    'SZR_ALL': 'Stara Zagora',
    'TGV_ALL': 'Targovishte',
    'HKV_ALL': 'Haskovo',
    'SHU_ALL': 'Shumen',
    'JAM_ALL': 'Yambol',
}

BY_REGION_MELT_VARS = ['Blagoevgrad', 'Burgas', 'Varna', 'Veliko Tarnovo', 'Vidin',
                       'Vratsa', 'Gabrovo', 'Dobrich', 'Kardzhali', 'Kyustendil', 'Lovech',
                       'Montana', 'Pazardzhik', 'Pernik', 'Pleven', 'Plovdiv', 'Razgrad',
                       'Ruse', 'Silistra', 'Sliven', 'Smolyan', 'Sofia', 'Sofia (stolitsa)',
                       'Stara Zagora', 'Targovishte', 'Haskovo', 'Shumen', 'Yambol']